### PR TITLE
v0.9.0

### LINKED ISSUE #200: The Back Handler is working，FlatView  dont't scroll
hello, The Back Handler is working，but FlatView is not working, dont't scroll 。
#195

### LINKED ISSUE #203: Action sheet shrinks when keyboard shows
This issue is actually weird because it doesn't always happen, so it's quite hard to reproduce. But I was able capture a screen recording of the issue happening.

I'm using 0.8.4

Here's the [snack](https://snack.expo.dev/@bobharlly/test-action-sheet-keyboard)
test-keyboard

### LINKED ISSUE #208: Opening, closing and content size calculation problem on iOS phones after 0.8.2 update.
Hello, I am using the new version of your package in a project I am currently developing. 
**After the [0.8.2 update](https://github.com/ammarahm-ed/react-native-actions-sheet/releases/tag/v0.8.2)**, I think there are some calculation errors when opening and closing sheet on **ios phones**. 
Sometimes everything works fine. Sometimes the **sheet opens but does not appear,** 
opens but **does not close completely** and **blocks touch actions**, etc... 
I guess the safe area guards you brought with 0.8.2 are breaking some calculations.
I tried opening the sheets both with reference and through the sheet manager and got the same result.

**Note:** I made a small patch to 0.8.1 and that's how I'm using it.
**Note 2:** I also tried it in versions 0.8.2, 0.8.3 and 0.8.4.

### LINKED ISSUE #220: Broken scrollHandlers
After changing `key` prop on `ScrollView/FlatList` breaks scrollHandlers. Any idea how to fix that?

### LINKED ISSUE #222: Additional space added in modal
Action sheet shows additional space in bottom of it.
It is random,one time it shows and the next time it doesn't.

Screenshot_20220925-120042_1
Screenshot_20220925-120106_1

### LINKED ISSUE #225: useScrollHandlers isn't allowing me to scroll
I'm using 0.8.7, and have a ScrollView in my ActionsSheet. I followed the guide, and set up the handler like this:

```tsx
 const actionSheetRef = useRef<ActionSheetRef>(null);

    const scrollHandlers = useScrollHandlers<ScrollView>(
      'scrollview-1',
      actionSheetRef,
    );
```

Then my action sheet like this:
```tsx
  <ActionSheet ref={actionSheetRef} gestureEnabled containerStyle={{backgroundColor: midnightBlue, height: 350, borderTopLeftRadius: 20, borderTopRightRadius: 20}}>
            <ScrollView  {...scrollHandlers}>
```

It renders the ActionSheet, but I can't scroll to the bottom of my list. Swiping up just kicks in the overscroll effect. Swiping down closes the ActionSheet, but is a little unreliable/sometimes laggy.

I'm using Expo Go in Android 13.

Any ideas? I like this library a lot, but right now this is preventing me from using it.

### LINKED ISSUE #229: When typing in Action Sheet, close the keyboard the bottom part of action sheet disappear for a few moment
https://user-images.githubusercontent.com/31057437/194734536-d1b98b88-a8cd-416c-8889-f3f281e473b6.MP4

When we have Text Input inside the Action Sheet, we have a blink for a moment for the backdrop keyboard. 
It's only happening when the text input is inside the action sheet.

> <ActionSheet
  id={sheetId}
  isModal={false}
  zIndex={zIndex}
  containerStyle={{
    height: '99%',
    backgroundColor: '#1A1A1A',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  }}
>

### LINKED ISSUE #235: keep the sheet open while gestureEnabled={true} and closeable={true}
I need to be able to close the bottom sheet when I navigate to different screens, so I use the prop `closeable={true}`, but I do not want the user to be able to close the sheet with a bottom swipe gesture. I need to keep `gestureEnabled={true}` because it still needs to be resized to different snapPoints. 

I am using the Action Sheet with SheetManager...

How can I remove the closing gesture? This would be similar to the prop `enablePanDownToClose` in other similar libraries.

Thanks!

```js
    <ActionSheet
      initialSnapIndex={1}
      snapPoints={[30, 70, 100]}
      backgroundInteractionEnabled
      closeOnPressBack={false}
      closeOnTouchBackdrop={false}
      closable
      gestureEnabled
      containerStyle={{
        backgroundColor: colors.midGray,
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
      }}
      indicatorStyle={{
        backgroundColor: colors.lightGray,
        width: 100,
      }}
      id={props.sheetId}
    >
```

### LINKED ISSUE #251: Payload props works only with onClose
Hi there, 

I have an action sheet component, that needs to return a text input value. I'm doing that using the payload props. 
The problem is, the return only works if I pass the onClose props too.. 

Here's my code: 

Action sheet component: 

```
import React, { useRef, useState } from 'react';
import { Text, View } from 'react-native';
import ActionSheet, { ActionSheetRef, SheetProps } from 'react-native-actions-sheet';
import { textStyles } from '../../../theme';
import i18n from '../../../i18n';
import Input from '../../../components/Input';

export const actionSheetMoodThoughtsID = 'actionSheetMoodThoughtsID';

const MoodActionSheet = (props: SheetProps<{ title: string; thoughts: string }>) => {
  const moodActionSheetRef = useRef<ActionSheetRef>(null);
  const [thoughts, setThoughts] = useState(props.payload?.thoughts);
  return (
    <ActionSheet id={actionSheetMoodThoughtsID} ref={moodActionSheetRef} payload={thoughts}>
      <View>
        <Text style={[textStyles.title, textStyles.semiBold, textStyles.center]}>
          {i18n.t(props.payload?.title || '')}
        </Text>
        <Input
          autoFocus
          rounded
          value={thoughts}
          onChangeText={(value: string) => setThoughts(value)}
          returnKeyType='default'
          multiline
          numberOfLines={4}
        />
      </View>
    </ActionSheet>
  );
};

export default MoodActionSheet;

```

the function that open and receive the value: 

```
  const handleActionSheet = async () => {
    const response: string = await SheetManager.show(actionSheetMoodThoughtsID, {
      payload: { title: 'mood_what_thoughts_went_through_your_head', thoughts },
    });
    console.log('response: ', response);
    setThoughts(response);
  };
```

that way, the response always receives `undefined` but if I update the action sheet to  `    <ActionSheet id={actionSheetMoodThoughtsID} ref={moodActionSheetRef} payload={thoughts} onClose={() => {})> ` then everything works fine, 

Version of the library: 0.8.10. 
Problem happens on IOS, not tested on Android yet

### LINKED ISSUE #270: Having height issue when i open keyboard
Hi there,

I am facing an issue with the latest version of the library where the height of the action sheet changes after I open the keyboard and close the action sheet. I have attached a video demonstrating the issue.

Interestingly, this issue is not present in an older version of the library, which leads me to believe that it is a regression bug. I would greatly appreciate any assistance in resolving this issue.

Thank you in advance for your help!

### LINKED ISSUE #280: Problem with show() immediately after await hide()
I have this onPress handler for a Text component (of which there are hundreds):

```
onPress={async () => {
  if (SheetManager.get("word-sheet")) {
    await SheetManager.hide("word-sheet")
  }
  SheetManager.show("word-sheet", {
    payload: { word: indword, language: bookData[docToSee as keyof typeof bookData].language },
  });
}}

```

The registered WordSheet allows backgroundInteractionEnabled. I want the user to be able to click on a word to see the action sheet and then click on a new word, have the previous word action sheet hide and then show the new word action sheet.

This doesn't seem to be working.
1. On subsequent clicks, the height of the WordSheet is very small, I can't even see the content of the action sheet.
2. If I dismiss the WordSheet via gestureEnabled, I can no longer click on new words.

I have also tried using hideAll(), but it didn't work at all.

My last resort was to add a timer to SheetManager.show, to run 10ms after await SheetManager.hide returns:
```
onPress={async () => {
  if (SheetManager.get("word-sheet") && SheetManager.get("word-sheet").current?.isOpen()) {
    await SheetManager.hide("word-sheet")
  }
  // wait 1ms for the sheet to hide
  setTimeout(() => {
    SheetManager.show("word-sheet", {
      payload: { word: indword, language: bookData[docToSee as keyof typeof bookData].language },
    });
  }, 10);
}}
```

This seems to be working! I played around a bit with the timing, 1 ms is too little and there was some cases where the WordSheet wouldn't show, or would render incorrectly, and I found the 10ms consistently worked.

### LINKED ISSUE #282: The action sheet does not close if there is another action sheet open below it
When I open an action sheet and then through a button I open another, this second one does not close.

This code is totally ignored--->      SheetManager.hide('action-sheet-id');

If I use them independently, they both close correctly.

I am using the same action sheet manager to manage them.

Can anybody help me?

### LINKED ISSUE #290: Sending `onAnimatedValueUpdate` with no listeners registered.
This warning has been launched when execute SheetManager.hide function. 
Captura de Pantalla 2023-05-02 a las 14 05 28

Obviously, the "animated" prop of the ActionSheet object must be set to true. If there is no animation, the warning is not triggered. 

¿Any ideas?

Thank you!

### LINKED ISSUE #291: keyboard issue
- #229

### LINKED ISSUE #293: Doesn't work in screen presentation modal.
Hello, I try to use the SheetManager inside a Screen View with modal presentation. Like this :

```
<Stack.Group screenOptions={{ presentation: 'modal'}} >
          <Stack.Screen name="MyComponent" component={MyComponent} options={{ headerShown: false }} />
</Stack.Group>

```
In MyComponent, SheetManager.show doesn't work but no error.
With normal Screen without presentation: modal it works, but it's not what i want.

Any idea or workaround ?  thanks for your help.

### LINKED ISSUE #294: handleChildScrollEnd has been removed. Please use `useScrollHandlers` hook to enable scrolling in ActionSheet
Documentation still states to use "handleChildScrollEnd" however it throws a warning:

"handleChildScrollEnd has been removed. Please use `useScrollHandlers` hook to enable scrolling in ActionSheet"

Example code:
                        actionSheetRef.current?.handleChildScrollEnd()

### LINKED ISSUE #297: (Suggestion) improve SheetManager with better typing
I'm currently using this library with the `SheetManager` in typescript, but i found it's typing can be improved. these are the things that i think can be improved:

1. you can put any string to `id` parameter in the `show` function, it should not, it should only accept registered `id`.
2. the `payload` type in `options` should depends on the `payload` of the sheet component that registered with the given `id`, not just by defining generic on the `show` function.
3. it just feel weird and "disconnected" when you need to import `registerSheet` to register a sheet, but use `SheetManager` to show and hide it.

So i already creating a solution for all of those problem, which you can see here (https://gist.github.com/prs-wjy/d92e44e026b0f93c95cae0e0d0e913df).

The only thing that i also want to improve is to make the `payload` parameter in the `show` function become required if only the sheet component with the `id` argument have required parameter on it's payload, but i don't know how to do it (i don't even know if it's possible 😅)

I want to make a pull request to make it the default behavior, but i never contribute to a library code nor any open source code, so i think it's just better for me to create this issue.

What do you guys think?

### LINKED ISSUE #299: Action sheet bottom space sometimes
Sometimes when I open the Action sheet it gives me some space on the button and sometimes it doesn't give me. The yellow border in the video should stay ever at the bottom of the screen....

```typescript
<ActionSheet
      drawUnderStatusBar={true}
      ref={actionSheetRef}
      closable={true}
      backgroundInteractionEnabled={false}
      // useBottomSafeAreaPadding={isKeyboardOpen}
      useBottomSafeAreaPadding={true}
      closeOnTouchBackdrop
      // gestureEnabled
      isModal={false}
      defaultOverlayOpacity={0.2}
      containerStyle={{
        display: 'flex',
        // flexDirection: 'column',
        // backgroundColor: theme['color-primary-BK'],
        backgroundColor: 'red',
        borderTopLeftRadius: GLOBAL_BORDER_RADIUS,
        borderTopRightRadius: GLOBAL_BORDER_RADIUS,
        borderColor: 'yellow',
        borderWidth: 1,
        paddingBottom: 0,
      }}
      keyboardHandlerEnabled={true}>
      <CategoryForm category={{}} />
    </ActionSheet>
``` 

This is the code of how I have implemented it.

I tried also to remove the **CategoryForm** component but it isn't the cause of the issue. The problem is in the Action sheet.

Pls help me!

https://github.com/ammarahm-ed/react-native-actions-sheet/assets/17024202/473b14a7-2e0f-47aa-ad94-c091b730a8f1

### LINKED ISSUE #303: useRouter is being returned as undefined function
When I follow the example for using routes, I get an error on the following line

const router = useRouter();

error says "undefined is not a function".

I import it as follows:

import ActionSheet, { useSheetRouteParams, useScrollHandlers, useRouter } from 'react-native-actions-sheet';

I honestly don't know what I am doing wrong.  The only difference is I am writing in javascript, not in typescript.

### LINKED ISSUE #304: @shopify/flash-list not found
minor bug fixed by installing the dependency, but should be listed as one

### LINKED ISSUE #305: where is 0.9.0-alpha come from?
I check `yarn outdated` see `react-native-actions-sheet` has a upgradable version `0.9.0-alpha.21`, but where is this version from? I search the repo and google, has no any info about it.

### LINKED ISSUE #310: [web] expo sdk >47 setNativeProps fix
i ran into a problem with expo sdk 49 and exporting to web and just wanted to share the fix for the deprecated setNativeProps implementation.
this is my patch from patch-package:
```
diff --git a/node_modules/react-native-actions-sheet/dist/src/index.js b/node_modules/react-native-actions-sheet/dist/src/index.js
index 064a25f..d403411 100644
--- a/node_modules/react-native-actions-sheet/dist/src/index.js
+++ b/node_modules/react-native-actions-sheet/dist/src/index.js
@@ -843,11 +843,11 @@ export default forwardRef(function ActionSheet(_a, ref) {
             windowDimensions.width < windowDimensions.height;
         if (orientationChanged)
             isOrientationChanging.current = true;
-        (_a = deviceContainerRef.current) === null || _a === void 0 ? void 0 : _a.setNativeProps({
-            style: {
-                height: Dimensions.get('screen').height - safeMarginFromTop
-            }
+        
+        (_a = deviceContainerRef.current) === null || _a === void 0 ? void 0 : setDimensions({
+            height: Dimensions.get('screen').height - safeMarginFromTop
         });
+        
         setDimensions(function (dim) {
             return __assign(__assign({}, dim), { height: height, portrait: windowDimensions.width < windowDimensions.height });
         });
```

### LINKED ISSUE #312: Latest version throws "@shopify/flash-list" error.
Installing the latest version throws a build error.  Apparently "@shopify/flash-list" was used in one of the files but couldn't be resolved.

iOS Bundling failed 434ms
Unable to resolve "@shopify/flash-list" from "node_modules/react-native-actions-sheet/dist/src/views/FlashList.js"

### LINKED ISSUE #316: No params passed to initial route
When using router i'm trying to pass params to the initial route

router is registered
```
registerSheet(
  'test_router',
  RouterSheet,
);
```

RouterSheet
```
  <ActionSheet
    enableRouterBackNavigation
    routes={routes}
    initialRoute={'initial_route'}
  />
```

Routes
```
const routes: Route[] = [
  {
    name: 'initial_route',
    component: InitialRouteComponent,
  },
 {
    name: 'second_route',
    component: SecondRouteComponent,
  },
];
```

i'm trying to navigate like so
```
SheetManager.show('test_router', {
  params: {
    test: 'test'
  }
}
```

inside my initial route i'm trying to get the params
```
const params = useSheetRouteParams();
```
but this is always undefiend

I did also try navigating to second route and pass params like so
```
return router?.navigate(
        'second_route',
        {
          test1: 'test1'
        },
      );
```
which works as expected

### LINKED ISSUE #318: [commonjs--resolver] Unexpected token => node_modules/react-native-actions-sheet/dist/src/index.js:785:12
Hello,

I have the following problem on desktop.
After including 'react-native-actions-sheet' @0.8.21, I get the following error message when building with vite:

```
[commonjs--resolver] Unexpected token (785:12) in D:/workspace/ActionsSheet/node_modules/react-native-actions-sheet/dist/
file: D:/workspace/ActionsSheet/node_modules/react-native-actions-sheet/dist/src/index.js:785:12
```
grafik

When I look into this file, I see that there is a JSX fragment in the .js file?!  And this is exactly what is detected as an error.

How can I fix this problem??

What does our environment look like ?
- Node 18
- React / React-Dom: 18.2.0
- Typescript 5.2.2
- Vite 4.4.11

### LINKED ISSUE #319: Uncaught TypeError: _a2.setNativeProps is not a function
Hello,
after my project with vite and 'react-native-actions-sheet' can finally be compiled (there were several settings in the vite.config.ts required) there is now a new problem.

When trying to display the component, the following error occurs (we use  react-native-actions-sheet @0.8.21, Storybook 7.4.6 for react-vite) :
grafik

grafik

The Component looks like this (and is only one part of my app):

```
import { useRef } from 'react'
import { Text, View } from 'react-native'
import ActionSheet, { ActionSheetRef, SheetProps } from 'react-native-actions-sheet'

export const AktionsbereichMobil = ({ sheetId, payload }: SheetProps<{ inhalt: string }>) => {
  console.log(payload?.inhalt)
  console.log(sheetId)

  const actionSheetRef = useRef<ActionSheetRef>(null)

  return (
    <ActionSheet
      id={sheetId}
      ref={actionSheetRef}
      containerStyle={{
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25
      }}
      indicatorStyle={{
        width: 100
      }}
      gestureEnabled={true}
    >
      <View>
        <Text>{payload?.inhalt}</Text>
      </View>
    </ActionSheet>
  )
}

export default AktionsbereichMobil
```

Sheets.tsx
```
import { registerSheet } from 'react-native-actions-sheet'
import { AktionsbereichMobil } from '../GUI-Komponenten/Aktionsbereich/Aktionsbereich/AktionsbereichMobil.tsx'

registerSheet('aktionsBereichMobil', AktionsbereichMobil)

export { }
```

Try to show:
`SheetManager.show('aktionsBereichMobil', { payload: { inhalt: 'TestString' } })`

console.log from component:
```
'TestString' => OK
'aktionsBereichMobil' => OK
```

Does anyone know what the problem is here?

### LINKED ISSUE #322: How to limit max expanded height?
How do you prevent a sheet from going beyond a max height or snap point? I have tried setting a snap point to 75 for example, but it will allow me to expand it even further, if there is content in the view large enough. The preference would be to set a limit for the max height and have the scroll view handle the overflow.

Here is an example of difference in functionality between platforms. We do not like the ios behavior of how it will up into the status bar. it should behave like android does
image

### LINKED ISSUE #325: Android does not overlap the navigation bar
Hi,
is there any way to remove navigation bar on bottom sheet on Android or changing color of it, where is the theme coming from, how can i override it? By the way it's already overlapping on IOS.

Screenshot 2023-12-13 at 11 11 34

### LINKED ISSUE #326: Sheet Manager does not work in react-native version 0.73.1
SheetManager is not working in react-antive 0.73.1 version. These action sheets cannot be managed with the provider. When SheetManager.show('sheetname') is run, no response is received. Since this feature does not work, sheets can be intervened with ref.

How can the Sheetmanager issue be resolved?

The issue is present in all 3 versions: 0.8.10, 0.8.29 and 0.9.0-alpha.24.

### LINKED ISSUE #329: Cannot open action sheet again when using closable={false}
I need to control the closable action sheet. For example, I select some items on the background list and the action list is not closable, if I click 'Cancel' it should close to the next handling. But `closable={false} backgroundInteractionEnabled={true} ` props doesn't work properly, can't open again and the app is stacked. Only helps reload the app.

```
"react-native-actions-sheet": "^0.8.29"
```

```
import React, { useRef } from 'react';
import { ScrollView } from 'react-native';
import ActionSheet, {
  ActionSheetRef,
  SheetManager,
  SheetProps,
  useScrollHandlers,
} from 'react-native-actions-sheet';
import { SheetButton } from '@/components/SheetButton';

function ScrollableActionsSheet({ sheetId }: SheetProps) {
  const actionSheetRef = useRef<ActionSheetRef>(null);
  const scrollHandlers = useScrollHandlers<ScrollView>(
    'scrollview-1',
    actionSheetRef
  );

  return (
    <ActionSheet
      ref={actionSheetRef}
      backgroundInteractionEnabled
      closable={false}
      drawUnderStatusBar
      enableGesturesInScrollView
      gestureEnabled
      id={sheetId}
      indicatorStyle={{ height: 4 }}
      snapPoints={[40, 60]}
    >
      <ScrollView {...scrollHandlers} style={{ maxHeight: 300 }}>
        <SheetButton
          color={'red'}
          onPress={() => SheetManager.hide(sheetId, { payload: false })}
          title='Cancel'
        />
        <SheetButton
          color={'red'}
          onPress={() => SheetManager.hide(sheetId, { payload: false })}
          title='Cancel'
        />
      </ScrollView>
    </ActionSheet>
  );
}

```

https://github.com/ammarahm-ed/react-native-actions-sheet/assets/42835486/ea240755-7177-46f8-9ecc-d0d769d886a7

### PR DESCRIPTION
**Pull request by ammarahm-ed**
Closes #304 
Closes #312
Closes #329 
Closes #326
Closes #325
Closes #322
Closes #319
Closes #318
Closes #316
Closes #310
Closes #305
Closes #303
Closes #299
Closes #297 
Closes #294 
Closes #293 
Closes #291 
Closes #290 
Closes #282
Closes #280
Closes #270
Closes #251
Closes #235
Closes #225
Closes #229 
Closes #222 
Closes #220 
Closes #208 
Closes #200
Closes #203

### CODE REVIEW

**Comment by Kreshnik** [comment]
@ammarahm-ed sorry for asking, but when will the new release be available?

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed sorry for asking, but when will the new release be available? 

Probably in a day or so.

**Comment by Sydney-o9** [comment]
Hello Team, is this packed in a new release by any chance?

**Comment by ziga-hvalec** [comment]
Why is this not marked as latest version? Latest release is stil 0.8.1

**Pull request merged**
